In [136]:
# เปิดไฟล์

import pandas as pd
import json

file_name="chaiya.csv"

# specify n rows
df = pd.read_csv(file_name, nrows = 1000)

# all data
# df = pd.read_csv(file_name)

df

,TIMESTAMP,LATITUDE,LONGITUDE,SPEED,DIRECTION,ENGINE,CARD,CARD_DRIVER,METER,METER_FARE,VEHICLE_ID
0,2020-05-22 06:11:44.000,13.68947,100.44334,0.0,44.7,ON,ON,CHAIYA,OFF,NaN,2000.0
1,2020-05-22 06:12:09.000,13.68947,100.44334,0.0,44.7,ON,ON,CHAIYA,OFF,NaN,2000.0
2,2020-05-22 06:12:39.000,13.68947,100.44334,0.0,44.7,ON,ON,CHAIYA,OFF,NaN,2000.0
3,2020-05-22 06:13:09.000,13.68927,100.44312,12.0,224.9,ON,ON,CHAIYA,OFF,NaN,2000.0
4,2020-05-22 06:13:39.000,13.68892,100.44243,24.0,318.6,ON,ON,CHAIYA,OFF,NaN,2000.0
...,...,...,...,...,...,...,...,...,...,...,...
995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [137]:
# algorithm

finalArray = []

car_running = False

tripNumber = 0
cardDriver = ""
pickupDateTime = 0
pickupLatitude = 0
pickupLongitude = 0

dropoffDateTime = 0
dropoffLatitude = 0
dropoffLongtitude = 0
meterFare = 0


for index, row in df.iterrows():
    
    # start meter
    if (not car_running and row["METER"] == "ON"):
        car_running = True
        # collect pickup data
        cardDriver = row["CARD_DRIVER"]
        pickupLatitude = row["LATITUDE"]
        pickupLongitude = row["LONGITUDE"]
        pickupDateTime = row["TIMESTAMP"]
        vehicleId = row["VEHICLE_ID"]
    

    
    if (car_running and row["METER"] == "OFF"):
        car_running = False
        # collect dropoff data
        item = {
            "TRIP_NUMBER": tripNumber,
            "VEHICAL_ID": vehicleId,
            "CARD_DRIVER": cardDriver,
            "PICKUP_DATETIME": pickupDateTime,
            "PICKUP_LATITUDE": pickupLatitude,
            "PICKUP_LONGTITUDE": pickupLongtitude,
            "DROPOFF_LATITUDE": dropoffLatitude,
            "DROPOFF_LONGTITUDE": dropoffLongtitude,
            "METER_FARE": meterFare
        }
        finalArray.append(item)
        tripNumber += 1
        
    meterFare = row["METER_FARE"]
    dropoffDateTime = row["TIMESTAMP"]
    dropoffLatitude = row["LATITUDE"]
    dropoffLongtitude = row["LONGITUDE"]
        
print(finalArray)

[{'TRIP_NUMBER': 0, 'VEHICAL_ID': 2000.0, 'CARD_DRIVER': 'CHAIYA', 'PICKUP_DATETIME': '2020-05-22 06:31:29.000', 'PICKUP_LATITUDE': 13.66285, 'PICKUP_LONGTITUDE': 100.47707, 'DROPOFF_LATITUDE': 13.64935, 'DROPOFF_LONGTITUDE': 100.42043, 'METER_FARE': 53.0}, {'TRIP_NUMBER': 1, 'VEHICAL_ID': 2000.0, 'CARD_DRIVER': 'CHAIYA', 'PICKUP_DATETIME': '2020-05-22 07:15:33.000', 'PICKUP_LATITUDE': 13.66335, 'PICKUP_LONGTITUDE': 100.47707, 'DROPOFF_LATITUDE': 13.67751, 'DROPOFF_LONGTITUDE': 100.51411, 'METER_FARE': 95.0}, {'TRIP_NUMBER': 2, 'VEHICAL_ID': 2000.0, 'CARD_DRIVER': 'CHAIYA', 'PICKUP_DATETIME': '2020-05-22 07:54:28.000', 'PICKUP_LATITUDE': 13.67915, 'PICKUP_LONGTITUDE': 100.47707, 'DROPOFF_LATITUDE': 13.67634, 'DROPOFF_LONGTITUDE': 100.46286, 'METER_FARE': 35.0}, {'TRIP_NUMBER': 3, 'VEHICAL_ID': 2000.0, 'CARD_DRIVER': 'CHAIYA', 'PICKUP_DATETIME': '2020-05-22 07:56:39.000', 'PICKUP_LATITUDE': 13.67425, 'PICKUP_LONGTITUDE': 100.47707, 'DROPOFF_LATITUDE': 13.78013, 'DROPOFF_LONGTITUDE': 100.42425, 'METER_FARE': 199.0}, {'TRIP_NUMBER': 4, 'VEHICAL_ID': 2000.0, 'CARD_DRIVER': 'CHAIYA', 'PICKUP_DATETIME': '2020-05-22 08:44:34.000', 'PICKUP_LATITUDE': 13.73814, 'PICKUP_LONGTITUDE': 100.47707, 'DROPOFF_LATITUDE': 13.73441, 'DROPOFF_LONGTITUDE': 100.44896, 'METER_FARE': 35.0}, {'TRIP_NUMBER': 5, 'VEHICAL_ID': 2000.0, 'CARD_DRIVER': 'CHAIYA', 'PICKUP_DATETIME': '2020-05-22 08:47:00.000', 'PICKUP_LATITUDE': 13.73092, 'PICKUP_LONGTITUDE': 100.47707, 'DROPOFF_LATITUDE': 13.70362, 'DROPOFF_LONGTITUDE': 100.40768, 'METER_FARE': 85.0}, {'TRIP_NUMBER': 6, 'VEHICAL_ID': 2000.0, 'CARD_DRIVER': 'CHAIYA', 'PICKUP_DATETIME': '2020-05-22 10:24:54.000', 'PICKUP_LATITUDE': 13.67297, 'PICKUP_LONGTITUDE': 100.47707, 'DROPOFF_LATITUDE': 13.67684, 'DROPOFF_LONGTITUDE': 100.4617, 'METER_FARE': 35.0}, {'TRIP_NUMBER': 7, 'VEHICAL_ID': 2000.0, 'CARD_DRIVER': 'CHAIYA', 'PICKUP_DATETIME': '2020-05-22 10:27:31.000', 'PICKUP_LATITUDE': 13.67827, 'PICKUP_LONGTITUDE': 100.47707, 'DROPOFF_LATITUDE': 13.67827, 'DROPOFF_LONGTITUDE': 100.46061, 'METER_FARE': 37.0}, {'TRIP_NUMBER': 8, 'VEHICAL_ID': 2000.0, 'CARD_DRIVER': 'CHAIYA', 'PICKUP_DATETIME': '2020-05-22 10:31:39.000', 'PICKUP_LATITUDE': 13.67998, 'PICKUP_LONGTITUDE': 100.47707, 'DROPOFF_LATITUDE': 13.74336, 'DROPOFF_LONGTITUDE': 100.5014, 'METER_FARE': 97.0}, {'TRIP_NUMBER': 9, 'VEHICAL_ID': 2000.0, 'CARD_DRIVER': 'CHAIYA', 'PICKUP_DATETIME': '2020-05-22 10:58:45.000', 'PICKUP_LATITUDE': 13.74435, 'PICKUP_LONGTITUDE': 100.47707, 'DROPOFF_LATITUDE': 13.74337, 'DROPOFF_LONGTITUDE': 100.49883, 'METER_FARE': 35.0}, {'TRIP_NUMBER': 10, 'VEHICAL_ID': 2000.0, 'CARD_DRIVER': 'CHAIYA', 'PICKUP_DATETIME': '2020-05-22 11:01:31.000', 'PICKUP_LATITUDE': 13.74182, 'PICKUP_LONGTITUDE': 100.47707, 'DROPOFF_LATITUDE': 13.75244, 'DROPOFF_LONGTITUDE': 100.48944, 'METER_FARE': 45.0}, {'TRIP_NUMBER': 11, 'VEHICAL_ID': 2000.0, 'CARD_DRIVER': 'CHAIYA', 'PICKUP_DATETIME': '2020-05-22 11:29:37.000', 'PICKUP_LATITUDE': 13.74222, 'PICKUP_LONGTITUDE': 100.47707, 'DROPOFF_LATITUDE': 13.74513, 'DROPOFF_LONGTITUDE': 100.49656, 'METER_FARE': 35.0}, {'TRIP_NUMBER': 12, 'VEHICAL_ID': 2000.0, 'CARD_DRIVER': 'CHAIYA', 'PICKUP_DATETIME': '2020-05-22 11:33:31.000', 'PICKUP_LATITUDE': 13.7423, 'PICKUP_LONGTITUDE': 100.47707, 'DROPOFF_LATITUDE': 13.72211, 'DROPOFF_LONGTITUDE': 100.50296, 'METER_FARE': 67.0}, {'TRIP_NUMBER': 13, 'VEHICAL_ID': 2000.0, 'CARD_DRIVER': 'CHAIYA', 'PICKUP_DATETIME': '2020-05-22 11:52:55.000', 'PICKUP_LATITUDE': 13.73048, 'PICKUP_LONGTITUDE': 100.47707, 'DROPOFF_LATITUDE': 13.73017, 'DROPOFF_LONGTITUDE': 100.50946, 'METER_FARE': 37.0}, {'TRIP_NUMBER': 14, 'VEHICAL_ID': 2000.0, 'CARD_DRIVER': 'CHAIYA', 'PICKUP_DATETIME': '2020-05-22 11:57:01.000', 'PICKUP_LATITUDE': 13.73004, 'PICKUP_LONGTITUDE': 100.47707, 'DROPOFF_LATITUDE': 13.70526, 'DROPOFF_LONGTITUDE': 100.60104, 'METER_FARE': 201.0}, {'TRIP_NUMBER': 15, 'VEHICAL_ID': 2000.0, 'CARD_DRIVER': 'CHAIYA', 'PICKUP_DATETIME': '2020-05-22 12:48:29.000', 'PICKUP_LATITUDE': 13.71513, 'PICKUP_LONGTITUDE': 100.47707, 'DROPOFF_LATITUDE': 13.73758, 'DROPOFF_LONGTITUDE': 100.51419, 'METER_FARE': 87.0}, {'TRIP_NUMBER': 16, 'VEHICAL_ID': 2000.0, 'CARD_DRIVER': 'CHAIYA', 'PICKUP_DATETIME': '2020-05-22 13:19:26.000', 'PICKUP_LATITUDE': 13.74283, 'PICKUP_LONGTITUDE': 100.47707, 'DROPOFF_LATITUDE': 13.74345, 'DROPOFF_LONGTITUDE': 100.50402, 'METER_FARE': 35.0}, {'TRIP_NUMBER': 17, 'VEHICAL_ID': 2000.0, 'CARD_DRIVER': 'CHAIYA', 'PICKUP_DATETIME': '2020-05-22 13:22:31.000', 'PICKUP_LATITUDE': 13.73745, 'PICKUP_LONGTITUDE': 100.47707, 'DROPOFF_LATITUDE': 13.72099, 'DROPOFF_LONGTITUDE': 100.46816, 'METER_FARE': 85.0}, {'TRIP_NUMBER': 18, 'VEHICAL_ID': 2000.0, 'CARD_DRIVER': 'CHAIYA', 'PICKUP_DATETIME': '2020-05-22 13:42:16.000', 'PICKUP_LATITUDE': 13.71907, 'PICKUP_LONGTITUDE': 100.47707, 'DROPOFF_LATITUDE': 13.71867, 'DROPOFF_LONGTITUDE': 100.47127, 'METER_FARE': 35.0}, {'TRIP_NUMBER': 19, 'VEHICAL_ID': 2000.0, 'CARD_DRIVER': 'CHAIYA', 'PICKUP_DATETIME': '2020-05-22 13:46:01.000', 'PICKUP_LATITUDE': 13.72074, 'PICKUP_LONGTITUDE': 100.47707, 'DROPOFF_LATITUDE': 13.72099, 'DROPOFF_LONGTITUDE': 100.4777, 'METER_FARE': 37.0}]

In [138]:
# เขียนไฟล์

import csv

with open('ควยชัยตอมทิ้งแล้วทิ้งอีก.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(["TRIP_NUMBER", "VEHICAL_ID", "CARD_DRIVER", "PICKUP_DATETIME", "PICKUP_LATITUDE", "PICKUP_LONGTITUDE", "DROPOFF_LATITUDE", "DROPOFF_LONGTITUDE", "METER_FARE"])
    
    for i in finalArray:
        writer.writerow([
            i["TRIP_NUMBER"],
            i["VEHICAL_ID"],
            i["CARD_DRIVER"],
            i["PICKUP_DATETIME"],
            i["PICKUP_LATITUDE"],
            i["PICKUP_LONGTITUDE"],
            i["DROPOFF_LATITUDE"],
            i["DROPOFF_LONGTITUDE"],
            i["METER_FARE"],
        ])